<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Pelatihan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get pelatihan by id_pelatihan
     */
    function get_pelatihan($id_pelatihan)
    {
        $this->db->select('*');
        $this->db->join('perusahaan', 'perusahaan.id_perusahaan= pelatihan.id_perusahaan');
        $this->db->order_by('id_pelatihan', 'desc');
        $this->db->where('id_pelatihan', $id_pelatihan);
        return $this->db->get('pelatihan')->row_array();
    }

    function get_all_pelatihan_byid($id_pelatihan)
    {
        $this->db->select('*');
        $this->db->join('perusahaan', 'perusahaan.id_perusahaan= pelatihan.id_perusahaan');
        $this->db->order_by('id_pelatihan', 'desc');
        $this->db->where('pelatihan.id_perusahaan', $id_pelatihan);
        return $this->db->get('pelatihan')->result_array();
    }

    public function get_pendaftar_by_pelatihan($id)
    {
        $this->db->select('*');
        $this->db->from('daftar_pelatihan');
        $this->db->join('pelatihan', 'pelatihan.id_pelatihan=daftar_pelatihan.id_pelatihan', 'left');
        $this->db->join('alumni', 'alumni.id_alumni=daftar_pelatihan.id_alumni', 'left');
        $this->db->where('daftar_pelatihan.id_pelatihan', $id);
        return $this->db->get()->result();
    }

    /*
     * Get all pelatihan
     */
    function get_all_pelatihan()
    {
        $this->db->select('*');
        $this->db->join('perusahaan', 'perusahaan.id_perusahaan= pelatihan.id_perusahaan');
        $this->db->order_by('id_pelatihan', 'desc');
        return $this->db->get('pelatihan')->result_array();
    }

    function get_all_pelatihan_new()
    {
        $this->db->select('*');
        $this->db->join('perusahaan', 'perusahaan.id_perusahaan= pelatihan.id_perusahaan');
        $this->db->order_by('id_pelatihan', 'desc');
        return $this->db->get('pelatihan')->result();
    }

    /*
     * function to add new pelatihan
     */
    function add_pelatihan($params)
    {
        $this->db->insert('pelatihan', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update pelatihan
     */
    function update_pelatihan($id_pelatihan, $params)
    {
        $this->db->where('id_pelatihan', $id_pelatihan);
        return $this->db->update('pelatihan', $params);
    }

    /*
     * function to delete pelatihan
     */
    function delete_pelatihan($id_pelatihan)
    {
        return $this->db->delete('pelatihan', array('id_pelatihan' => $id_pelatihan));
    }
}
